# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-26 08:38
from __future__ import unicode_literals

import bookcase.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bookcase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='add_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='author',
            name='face',
            field=models.ImageField(blank=True, null=True, upload_to=bookcase.models.upload_logo),
        ),
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to=bookcase.models.upload_logo),
        ),
    ]
