# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-28 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookcase', '0003_book_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True, default='description not available', null=True),
        ),
    ]
