# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-28 17:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookcase', '0006_auto_20160628_1858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='approved_review',
        ),
        migrations.AddField(
            model_name='author',
            name='approved',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='book',
            name='approved',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='review',
            name='approved',
            field=models.BooleanField(default=True),
        ),
    ]
